### ISSUE TITLE
Some issues with the Registration Window

### ISSUE THREAD

**Issue by remusache** [jamfprofessionalservices/DEPNotify#12]
Hey @kbareis 

I'm stressing you again… 😜
I seem to have a little bit of an issue with the latest script - 1.2.0
The registration window comes up twice: once in the beginning of the installation and once more at the end. And at the end, I have no option to close the DEPNotify window.
I'll attach some screens to better explain what I mean.

<img width="812" alt="screen 1" src="https://user-images.githubusercontent.com/43576241/48121810-33549680-e276-11e8-9545-aa78d4932cea.png">
<img width="812" alt="screen 2" src="https://user-images.githubusercontent.com/43576241/48121813-38b1e100-e276-11e8-8f4b-e0471a955a92.png">
<img width="812" alt="screen 3" src="https://user-images.githubusercontent.com/43576241/48121817-3bacd180-e276-11e8-9892-9b2881f89d16.png">
<img width="812" alt="screen 4" src="https://user-images.githubusercontent.com/43576241/48121824-40718580-e276-11e8-8f5f-4cbc3d6179b3.png">
<img width="812" alt="screen 5" src="https://user-images.githubusercontent.com/43576241/48121834-45363980-e276-11e8-95a5-d499c7ff22ba.png">
<img width="812" alt="screen 6" src="https://user-images.githubusercontent.com/43576241/48121840-48c9c080-e276-11e8-8c59-6910af2715c1.png">
<img width="812" alt="screen 7" src="https://user-images.githubusercontent.com/43576241/48121844-4a938400-e276-11e8-93d7-24bc234a81ee.png">

[depNotify-New.sh.zip](https://github.com/jamfprofessionalservices/DEPNotify/files/2556800/depNotify-New.sh.zip)

**Comment by Hugonauts** [comment]
Same thing happens to me but the end of my modified version of your script removes depnotify and  boots the machine so its not as of a big deal, this is an issue though =)

**Comment by kbareis** [comment]
Hi @remusache and @Hugonauts! Sorry if I didn't make this as clear as I could. The script version 1.2.0 requires DEPNotify version 1.1.2. @mactroll dropped it on Friday in the Slack channel #depnotify. You can find it at this link: https://macadmins.slack.com/archives/C523HLQ83/p1541190679125900

The 1.1.2 update of DEPNotify adds a fix for registration and login windows as well as dark mode. @mactroll has updated the core code on the GitLab repo for DEPNotify but I do not think there is a PKG installer yet. I used Composer to create a quick package installer from the zip file that I linked above.

**Comment by kbareis** [comment]
@remusache and @Hugonauts Did that link work for you? Please update this ticket after you have had some time to test.

**Comment by remusache** [comment]
I used the DEPNotify from the link you provided us with and I am happy to report that is now working for me.
Thank you!
